# Generated by Django 4.2.4 on 2023-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturlusage",
            name="browser",
            field=models.CharField(default="Chrome", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shorturlusage",
            name="device",
            field=models.CharField(max_length=10),
        ),
    ]
