# Generated by Django 4.2.4 on 2023-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_alter_shorturlusage_date_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturlusage",
            name="date_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date used"),
        ),
    ]
