# Generated by Django 4.2.4 on 2023-08-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlhashmap",
            name="longurl",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="urlhashmap",
            name="shorturl",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
