# Generated by Django 4.2.4 on 2023-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_urlhashmap_longurl_alter_urlhashmap_shorturl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urlhashmap",
            name="longurl",
            field=models.CharField(max_length=255),
        ),
    ]
